interface e1-99
  ip address 10.0.1.254/24
  ip ospf 1 area 0
  ip ospf cost 10

interface e1-2
  ip address 10.0.2.12/24
  ip ospf 1 area 0
  ip ospf cost 1000

interface e1-3
  ip address 10.0.2.13/24
  ip ospf 1 area 0
  ip ospf cost 10

interface lo
  ip address 10.0.99.1/32

router ospf 1
  ospf router-id 10.0.99.1
