interface e2-1
  ip address 10.0.2.21/24
  ip ospf 1 area 0
  ip ospf cost 1000

interface e2-3
  ip address 10.0.2.23/24
  ip ospf 1 area 0
  ip ospf cost 100

interface e2-4
  ip address 10.0.2.24/24
  ip ospf 1 area 0
  ip ospf cost 1000

interface lo
  ip address 10.0.99.2/32

router ospf 1
  ospf router-id 10.0.99.2
