interface e3-1
  ip address 10.0.2.31/24
  ip ospf 1 area 0
  ip ospf cost 10

interface e3-2
  ip address 10.0.2.32/24
  ip ospf 1 area 0
  ip ospf cost 100

interface e3-4
  ip address 10.0.2.34/24
  ip ospf 1 area 0
  ip ospf cost 10

interface lo
  ip address 10.0.99.3/32

router ospf 1
  ospf router-id 10.0.99.3
