interface e4-2
  ip address 10.0.2.42/24
  ip ospf 1 area 0
  ip ospf cost 1000

interface e4-3
  ip address 10.0.2.43/24
  ip ospf 1 area 0
  ip ospf cost 10

interface e4-99
  ip address 10.0.3.254/24
  ip ospf 1 area 0
  ip ospf cost 10

interface lo
  ip address 10.0.99.4/32

router ospf 1
  ospf router-id 10.0.99.4
